SID= 'TWILIO SID HERE'
AUTH_TOKEN= 'TWILIO AUTH TOKEN HERE'
FROM_NUMBER='TWILIO GENERATED NUMBER HERE'
TO_NUMBER= 'RECIPIENT MOBILE NUMBER HERE'

MAILGUN_API_KEY = 'MAILGUN API KEY HERE'


SANDBOX_URL= 'MAILGUN SANBOX URL HERE'

SENDER_EMAIL = 'MAILGUN EMAIL HERE'

RECIPIENT_EMAIL = 'RECIPIENT EMAIL HERE'
API_KEY = "BOLT API KEY HERE"
DEVICE_ID = "BOLT DEVICE ID HERE"
